#!/bin/bash
# Privacy-Aware Model Setup for Free Model Comparison
# First-time setup: asks user privacy preferences and stores them
# Can be re-run anytime to modify preferences

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/.privacy-config"
REGISTRY_FILE="$SCRIPT_DIR/privacy-tier-registry.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ============================================================
# Helper functions
# ============================================================

print_header() {
    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║     Privacy-Aware Free Model Configuration              ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_tier_info() {
    local tier=$1
    case $tier in
        1)
            echo -e "${GREEN}TIER 1 — Strict Privacy${NC}"
            echo "  No data used for training. Zero-retention."
            echo "  No logging for improvement."
            echo ""
            echo -e "  ${YELLOW}Available models: None (no free models meet strict privacy)${NC}"
            echo -e "  ${YELLOW}⚠ You lose: MiMo (best reasoning),${NC}"
            echo -e "  ${YELLOW}  Ling Flash (fast docs), Big Pickle, Muse Spark${NC}"
            ;;
        2)
            echo -e "${GREEN}TIER 2 — Anonymous Improvement Only${NC}"
            echo "  Data logged for service improvement, NOT linked to identity."
            echo "  No model training."
            echo ""
            echo -e "  ${YELLOW}Available models: Nemotron Ultra, Nemotron Lightning${NC}"
            echo -e "  ${YELLOW}⚠ You lose: MiMo, Ling Flash, Big Pickle, Muse Spark${NC}"
            ;;
        3)
            echo -e "${GREEN}TIER 3 — Model Improvement${NC}"
            echo "  Data may be used to improve the model during free period."
            echo "  Not linked to identity."
            echo ""
            echo -e "  ${YELLOW}Available models: all except tier-4 (Muse Spark x2, DeepSeek Free unverified)${NC}"
            echo -e "  ${YELLOW}⚠ Tier-4 excluded: Muse Spark trains Meta; DeepSeek Free has no privacy info${NC}"
            ;;
        4)
            echo -e "${GREEN}TIER 4 — Accept All${NC}"
            echo "  All models available including those that train on your data."
            echo "  You explicitly accept that some providers use your prompts"
            echo "  and completions to train their models."
            echo ""
            echo -e "  ${YELLOW}Available models: ALL 10 free models${NC}"
            echo -e "  ${YELLOW}⚠ Muse Spark: your data trains future Meta models${NC}"
            echo -e "  ${YELLOW}⚠ DeepSeek Free: no privacy info — worst-case assumed${NC}"
            ;;
    esac
}

get_models_for_tier() {
    local max_tier=$1
    local models=()
    
    # Read registry and filter by tier
    while IFS= read -r line; do
        local model_id=$(echo "$line" | cut -d'|' -f1)
        local tier_num=$(echo "$line" | cut -d'|' -f2)
        if [ "$tier_num" -le "$max_tier" ] 2>/dev/null; then
            models+=("$model_id")
        fi
    done < <(jq -r '.models | to_entries[] | "\(.value.privacy_tier | split("_")[0])|\(.key)"' "$REGISTRY_FILE" 2>/dev/null | sort -t'|' -k2 -n)
    
    printf '%s\n' "${models[@]}"
}

save_config() {
    local tier=$1
    local timestamp=$(date -Iseconds)
    
    cat > "$CONFIG_FILE" << EOF
# Privacy Configuration for Free Model Comparison
# Generated by privacy-setup.sh
# DO NOT EDIT MANUALLY — run ./privacy-setup.sh to modify

privacy_max_tier=$tier
created_at=$timestamp
last_modified=$timestamp
version=1.0.0
EOF
    
    echo -e "${GREEN}✓ Configuration saved to $CONFIG_FILE${NC}"
}

load_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        return 1
    fi
    
    # Source the config
    source "$CONFIG_FILE"
    echo "$privacy_max_tier"
}

show_current_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        echo -e "${RED}No configuration found. First-time setup required.${NC}"
        return 1
    fi
    
    source "$CONFIG_FILE"
    
    echo -e "${BOLD}Current Configuration:${NC}"
    echo "  Privacy tier: $privacy_max_tier"
    echo "  Last modified: $last_modified"
    echo ""
    
    print_tier_info "$privacy_max_tier"
    
    echo -e "${BOLD}Models available at your tier:${NC}"
    local count=0
    while IFS= read -r model_id; do
        if [ -n "$model_id" ]; then
            local name=$(jq -r ".models[\"$model_id\"].name // \"$model_id\"" "$REGISTRY_FILE" 2>/dev/null)
            local provider=$(jq -r ".models[\"$model_id\"].provider // \"Unknown\"" "$REGISTRY_FILE" 2>/dev/null)
            echo "  ✓ $name ($provider) — $model_id"
            count=$((count + 1))
        fi
    done < <(get_models_for_tier "$privacy_max_tier")
    echo ""
    echo "  Total: $count models available"
}

# ============================================================
# Main setup flow
# ============================================================

print_header

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is required but not installed.${NC}"
    echo "Install with: sudo apt install jq"
    exit 1
fi

# Check if registry exists
if [ ! -f "$REGISTRY_FILE" ]; then
    echo -e "${RED}Error: privacy-tier-registry.json not found at $REGISTRY_FILE${NC}"
    exit 1
fi

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${CYAN}Existing configuration detected.${NC}"
    echo ""
    show_current_config
    echo ""
    echo -e "${BOLD}What would you like to do?${NC}"
    echo "  1) Keep current settings"
    echo "  2) Change privacy tier"
    echo "  3) View all models and their privacy details"
    echo "  4) Exit"
    echo ""
    read -p "Select option [1-4]: " choice
    
    case $choice in
        1)
            echo -e "${GREEN}Keeping current settings.${NC}"
            exit 0
            ;;
        2)
            echo ""
            echo -e "${BOLD}Changing privacy tier...${NC}"
            ;;
        3)
            echo ""
            echo -e "${BOLD}All models and their privacy details:${NC}"
            echo ""
            jq -r '.models | to_entries[] | 
                "Model: \(.value.name)\nProvider: \(.value.privacy_tier)\nTier: \(.value.privacy_tier)\nEvidence: \(.value.evidence)\n"' \
                "$REGISTRY_FILE" 2>/dev/null
            echo ""
            read -p "Press Enter to continue..."
            echo ""
            show_current_config
            exit 0
            ;;
        4)
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid option. Keeping current settings.${NC}"
            exit 0
            ;;
    esac
fi

# ============================================================
# First-time setup / tier selection
# ============================================================

echo -e "${BOLD}Choose your privacy level:${NC}"
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │  1  Strict Privacy                                      │"
echo "  │     No data used for training. Zero-retention.          │"
echo "  │     ⚠ Only Nemotron models (2 of 8)                    │"
echo "  │                                                         │"
echo "  │  2  Anonymous Improvement Only                          │"
echo "  │     Logged for improvement, NOT linked to identity.     │"
echo "  │     ⚠ Only Nemotron models (2 of 8)                    │"
echo "  │                                                         │"
echo "  │  3  Model Improvement (Recommended)                     │"
echo "  │     Data may improve the model during free period.      │"
echo "  │     ✓ 7 of 8 models — excludes Muse Spark              │"
echo "  │                                                         │"
echo "  │  4  Accept All                                          │"
echo "  │     All models available including Meta training.       │"
echo "  │     ⚠ Muse Spark trains Meta future models             │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
read -p "Select privacy tier [1-4]: " tier

# Validate input
if [[ ! "$tier" =~ ^[1-4]$ ]]; then
    echo -e "${RED}Invalid selection. Please enter 1, 2, 3, or 4.${NC}"
    exit 1
fi

echo ""
print_tier_info "$tier"

echo ""
echo -e "${BOLD}Models you'll have access to:${NC}"
while IFS= read -r model_id; do
    if [ -n "$model_id" ]; then
        name=$(jq -r ".models[\"$model_id\"].name // \"$model_id\"" "$REGISTRY_FILE" 2>/dev/null)
        provider=$(jq -r ".models[\"$model_id\"].provider // \"Unknown\"" "$REGISTRY_FILE" 2>/dev/null)
        echo "  ✓ $name ($provider)"
    fi
done < <(get_models_for_tier "$tier")

echo ""
echo -e "${BOLD}Models excluded at tier $tier:${NC}"
while IFS= read -r model_id; do
    if [ -n "$model_id" ]; then
        name=$(jq -r ".models[\"$model_id\"].name // \"$model_id\"" "$REGISTRY_FILE" 2>/dev/null)
        tier_name=$(jq -r ".models[\"$model_id\"].privacy_tier // \"unknown\"" "$REGISTRY_FILE" 2>/dev/null)
        echo "  ✗ $name (tier: $tier_name)"
    fi
done < <(jq -r '.models | to_entries[] | select(
    (.value.privacy_tier | split("_")[0] | tonumber) > '"$tier"'
) | .key' "$REGISTRY_FILE" 2>/dev/null)

echo ""
read -p "Confirm this selection? [Y/n]: " confirm
if [[ "$confirm" =~ ^[nN]$ ]]; then
    echo -e "${YELLOW}Setup cancelled.${NC}"
    exit 0
fi

save_config "$tier"

echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo "Your privacy tier ($tier) is now saved and will be used by:"
echo "  • model-selector.sh — picks best models for your tier"
echo "  • check-model-changes.sh — notifies when models change"
echo "  • test-models.sh — only tests models in your tier"
echo ""
echo "To change your preferences later, run:"
echo "  ./privacy-setup.sh"
